### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by bendichter** [SpikeInterface/spikemetrics#8]
I'm working with @ybernaerts on a project that has spikemetrics as a dependency and it is not installing on his machine (though it does on mine: OSX, py3.7). Here is the installation error:

```
     ERROR: Command errored out with exit status 1:
      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; 
sys.argv[0] = 
'"'"'/tmp/pip-install-uiuoi81e/spikemetrics/setup.py'"'"'; 
__file__='"'"'/tmp/pip-install-uiuoi81e/spikemetrics/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 
/tmp/pip-install-uiuoi81e/spikemetrics/pip-egg-info
          cwd: /tmp/pip-install-uiuoi81e/spikemetrics/
     Complete output (7 lines):
     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-install-uiuoi81e/spikemetrics/setup.py", line 6, 
in <module>
         long_description = open("README.md").read()
       File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
         return codecs.ascii_decode(input, self.errors)[0]
     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in 
position 406: ordinal not in range(128)
```

It looks like ascii is struggling with the README file due to a non-standard symbol. Looking at the file I am guessing the χ symbol is the offending character. I'm not quite sure why it installs on my computer and not Yves'. We are both using python 3. Yves, do you have any other system config information that might be helpful?

It looks like this stackoverflow thread https://stackoverflow.com/questions/16508539/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc2 might be useful

**Comment by ybernaerts** [comment]
So I'm pretty sure it is actually a charachter in the README file. When I installed it locally after cloning and removed everything up to the 2 first lines, it seems to work.

**Comment by alejoe91** [comment]
Hi guys! That's strange. I guess we could change the χ symbol to an X!

**Comment by alejoe91** [comment]
or just chi-squared. I'll fix it in the next days

**Comment by alejoe91** [comment]
857cb2ba00afa137a14d8fc7761480a76e74c74c

We'll make a new release and it should fix it.
@ybernaerts can you try to pull master and reinstall from sources? just to double check that this solves the issue

**Comment by ybernaerts** [comment]
I tried, but it did not fix it. I suspected it might due to line 6:
"Copyright © 2019. Allen Institute. All rights reserved." so the copyright symbol, but it also doesn't seem to be that. I guess it also shouldn't.

I'm still not sure what character it could be.

**Comment by ybernaerts** [comment]
Actually I do seem to have to delete this sentence in particular to not have this ASCII error to appear anymore.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikemetrics/commit/857cb2ba00afa137a14d8fc7761480a76e74c74c

Removed the copyright symbol then :)

**Comment by ybernaerts** [comment]
Thank you for looking into this annoying issue @alejoe91 . It seems to still not work unless I completely remove the sentence. No, I have no idea why anymore.
@bendichter When I remove the sentence this package is installed correctly. When I, however, try to install your package afterwards it also seems to install well in my environment, but when I start working in my standard Jupyter Notebooks, nothing seems to run anymore after installing your package (it does work well still after installing spikemetrics) and eventually the Docker Container crashes. I guess that, considering our project that you mentioned above in this issue, I might eventually leave the ephys data uploading to you.

Again, thanks guys for all the effort.

**Comment by alejoe91** [comment]
@ybernaerts is this still an issue?

**Comment by ybernaerts** [comment]
I don't think so. Perhaps one can close the issue.
